# Generated by Django 5.2.4 on 2025-07-08 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default=' ', upload_to='etudiant/images/'),
            preserve_default=False,
        ),
    ]
